# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	minecraft_version=1.20.1
	yarn_mappings=10
	fabric_loader_version=0.16.9
	fabric_api_version=0.92.2

# Dependency Properties
	jei_version=15.20.0.106
	jade_version_id=5771000

# Mod Properties
	mod_version = 0.2.0
	maven_group = net.stockieslad.magical_utilities
	modid=magical_utilities
	mod_name=Magical Utilities
